repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
        files: ^.*\.js$
      - id: trailing-whitespace
      - id: detect-private-key

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "" # Use the sha / tag you want to point at
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "" # Use the sha / tag you want to point at
    hooks:
      - id: eslint
        name: Lint and fix JavaScript
        args: [--fix, --max-warnings, "0", --color]
        additional_dependencies:
          - eslint
          - eslint-config-google
