const ENVIRONMENT_KEYS_REQUIRE = [
  'XRAY_CLIENT_ID',
  'XRAY_CLIENT_SECRET',
  'XRAY_PROJECT_ID',
  'JIRA_HOST',
  'JIRA_USERNAME',
  'JIRA_TOKEN',
];

exports.ENVIRONMENT_KEYS_REQUIRE = ENVIRONMENT_KEYS_REQUIRE;
